spring:
  cloud:
    gateway:
      routes:
        - uri: https://github.com
          predicates:
            - Path=/github/**
            - CustomWASMPredicate=
          filters:
            - StripPrefix=1